"""add_user_isolation_and_cascade_delete

Revision ID: 2ec61f38a5be
Revises: 17462152540a
Create Date: 2025-09-12 12:42:02.479988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec61f38a5be'
down_revision: Union[str, Sequence[str], None] = '17462152540a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. 先加可空列
    op.add_column('articles', sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID'))

    # 2. 给已有数据填充默认 user_id（这里假设 user_id=1 可用，按实际情况改）
    op.execute('UPDATE articles SET user_id = 1 WHERE user_id IS NULL')

    # 3. 再改为非空
    op.alter_column('articles', 'user_id', nullable=False)

    # 4. 外键调整
    op.drop_constraint(op.f('articles_source_id_fkey'), 'articles', type_='foreignkey')
    op.create_foreign_key(None, 'articles', 'content_sources', ['source_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'articles', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # 5. content_sources 表同理处理
    op.add_column('content_sources', sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID'))
    op.execute('UPDATE content_sources SET user_id = 1 WHERE user_id IS NULL')
    op.alter_column('content_sources', 'user_id', nullable=False)
    op.create_foreign_key(None, 'content_sources', 'users', ['user_id'], ['id'], ondelete='CASCADE')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content_sources', type_='foreignkey')
    op.drop_column('content_sources', 'user_id')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key(op.f('articles_source_id_fkey'), 'articles', 'content_sources', ['source_id'], ['id'], onupdate='CASCADE')
    op.drop_column('articles', 'user_id')
    # ### end Alembic commands ###
